import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
const seed = JSON.parse(readFileSync('src/data/initial-trip.json', 'utf8'))

async function ready(page: Page) {
  await page.goto('/')
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  if (await page.getByRole('button', { name: 'Dismiss', exact: true }).isVisible()) await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
}
async function route(page: Page, path: string) { await page.evaluate(p => { location.hash = p }, `#/${path}`) }
async function openDayNote(page: Page) { await page.getByRole('button', { name: /(?:Add|Edit) day note/ }).click() }
async function save(page: Page) { await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toHaveCount(0) }
async function exportData(page: Page) {
  await route(page, 'more')
  const button = page.getByRole('button', { name: 'Export trip data', exact: true })
  if (!await button.isVisible()) await page.getByText('Trip data', { exact: true }).click()
  const downloading = page.waitForEvent('download')
  await button.click()
  const stream = await (await downloading).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  return Buffer.concat(chunks)
}

test('offline CRUD, shared notes, booking propagation, move and exclusive alternatives', async ({ page, context }) => {
  await ready(page)
  await context.setOffline(true)
  await route(page, 'new/day-2')
  await page.getByLabel('Type', { exact: true }).selectOption('restaurant')
  await page.getByLabel('Name', { exact: true }).fill('Traveller lunch')
  await page.getByText('Place details & notes (optional)', { exact: true }).click()
  await page.getByLabel('Navigation link').fill('https://maps.google.com/?q=Llanes')
  await page.getByText('Booking details (optional)', { exact: true }).click()
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('13:15')
  await save(page)
  await expect(page.locator('.timeline').getByText('Traveller lunch', { exact: true }).first()).toBeVisible()
  const restaurant = page.locator('.timeline li').filter({ has: page.getByRole('heading', { name: 'Traveller lunch', exact: true }) })
  await expect(restaurant).toContainText('Confirmed · 13:15')
  await restaurant.getByRole('link', { name: 'Edit Traveller lunch', exact: true }).click()
  await page.getByLabel('Day', { exact: true }).selectOption('day-3')
  await save(page)
  await expect(page).toHaveURL(/day-3$/)
  const data = JSON.parse((await exportData(page)).toString())
  const entity = data.entities.find((e: { name: string }) => e.name === 'Traveller lunch')
  await route(page, `entity/${entity.id}`)
  await page.getByLabel('Place notes', { exact: true }).fill('Terrace if dry')
  await save(page)
  await page.reload()
  await expect(page.getByText('Terrace if dry', { exact: true })).toBeVisible()
  await route(page, 'item/day-3-item-2')
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('10:00')
  await page.getByLabel('Arrive before', { exact: true }).fill('09:30')
  await save(page)
  await route(page, 'more')
  await page.getByText('Booking & check actions', { exact: true }).click()
  const action = page.locator('.checklist>div').filter({ has: page.getByRole('heading', { name: 'El Soplao', exact: true }) })
  await expect(action).toContainText('Resolved')
  await route(page, 'day/day-12')
  const morningChoice = page.locator('.timeline li').filter({ hasText: 'Day 12 morning: Las Xanas or Naranco' })
  await expect(morningChoice.locator('.choice-option')).toHaveCount(2)
  await morningChoice.getByRole('button', { name: /View details for Las Xanas/ }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Choose this option' }).click()
  await expect(morningChoice.locator('.choice-option').filter({ hasText: 'Go directly to Naranco' })).toContainText('Not selected')
  await route(page, `entity/${entity.id}`)
  await page.getByRole('button', { name: 'Delete unused place' }).click()
  await expect(page.getByRole('alert')).toContainText('still used')
  const visit = data.days[2].items.find((i: { entityIds: string[] }) => i.entityIds.includes(entity.id))
  await route(page, `item/${visit.id}`)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Remove scheduled visit' }).click()
  await expect(page).toHaveURL(/day-3$/)
  await route(page, `entity/${entity.id}`)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Delete unused place' }).click()
  await expect(page).toHaveURL(/explore$/)
  await page.reload()
  await page.getByRole('searchbox').fill('Traveller lunch')
  await expect(page.getByText('No places match that search.', { exact: false })).toBeVisible()
})

test('cross-context export/import, rejection, cancellation and atomic backup restore', async ({ page, browser }) => {
  await ready(page)
  await openDayNote(page)
  await page.getByLabel('Day note', { exact: true }).fill('From phone one')
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Note saved')
  await route(page, 'documents')
  await page.getByRole('button', { name: 'Add shortcut', exact: true }).click()
  await page.getByLabel('Shortcut 1 name').fill('Trip folder')
  await page.getByLabel('Shortcut 1 URL').fill('https://drive.google.com/drive/folders/example')
  await save(page)
  const exported = await exportData(page)
  const second = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const receiver = await second.newPage()
  await receiver.goto('http://127.0.0.1:4173/#/more')
  await receiver.getByText('Trip data', { exact: true }).click()
  const upload = receiver.getByLabel('Import trip data', { exact: true })
  await upload.setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{ nope') })
  await expect(receiver.getByRole('status')).toContainText('not a compatible')
  await upload.setInputFiles({ name: 'future.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...seed, schemaVersion: 99 })) })
  await expect(receiver.getByRole('status')).toContainText('not a compatible')
  await upload.setInputFiles({ name: 'trip.json', mimeType: 'application/json', buffer: exported })
  await receiver.getByRole('button', { name: 'Cancel replacement' }).click()
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('')
  await upload.setInputFiles({ name: 'trip.json', mimeType: 'application/json', buffer: exported })
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  const result = JSON.parse((await exportData(receiver)).toString())
  const original = JSON.parse(exported.toString())
  expect({ ...result, revision: 0, updatedAt: '' }).toEqual({ ...original, revision: 0, updatedAt: '' })
  await receiver.getByRole('button', { name: 'Review saved backup' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('')
  await receiver.getByRole('button', { name: 'Review saved backup' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('From phone one')
  await receiver.getByRole('button', { name: 'Reset to initial trip' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('reset to the bundled initial data')
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('')
  await receiver.getByRole('button', { name: 'Review saved backup' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('From phone one')
  await second.close()
})

test('stale-tab writes retain the complete form draft and protect navigation', async ({ page, context }) => {
  await page.goto('/#/entity/restaurant-don-paco')
  await page.getByLabel('Place notes', { exact: true }).fill('Keep this private draft')
  page.once('dialog', d => d.dismiss())
  await page.getByRole('link', { name: 'More', exact: true }).click()
  await expect(page.getByLabel('Place notes', { exact: true })).toHaveValue('Keep this private draft')
  const other = await context.newPage()
  await other.goto('/')
  await openDayNote(other)
  await other.getByLabel('Day note', { exact: true }).fill('Concurrent save')
  await other.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(other.getByRole('status')).toContainText('Note saved')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('another tab')
  await expect(page.getByLabel('Place notes', { exact: true })).toHaveValue('Keep this private draft')
})

test('mobile form and browsing screens fit the viewport', async ({ page }) => {
  await page.goto('/#/new/day-1')
  await page.getByLabel('Type', { exact: true }).selectOption('hotel')
  await page.screenshot({ path: 'test-results/phase2-hotel-form.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  page.once('dialog', d => d.accept())
  await route(page, 'explore')
  await page.getByRole('button', { name: 'activity', exact: true }).click()
  await page.getByLabel('Plan', { exact: true }).selectOption('alternative')
  await page.screenshot({ path: 'test-results/phase2-explore.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await route(page, 'trip')
  await page.screenshot({ path: 'test-results/phase3-trip.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await route(page, 'more')
  await expect(page.getByText('Practical notes', { exact: true })).toHaveCount(0)
  await page.getByText('Trip data', { exact: true }).click()
  await expect(page.locator('.export-panel')).toBeVisible()
  await page.screenshot({ path: 'test-results/phase3-more.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('Today uses the compact ordered flow and activity sheet', async ({ page }) => {
  await page.goto('/#/today/day-2')
  const selector = page.getByRole('navigation', { name: 'Choose a trip date' })
  const title = page.getByRole('heading', { name: 'Llanes · Lagos de Covadonga' })
  const ahead = page.getByRole('heading', { name: 'The day ahead' })
  const hotel = page.locator('.hotel-panel')
  const review = page.getByRole('heading', { name: 'Actions & bookings to review' })
  const tomorrow = page.locator('.tomorrow')
  const y = async (locator: ReturnType<Page['locator']>) => (await locator.boundingBox())!.y
  expect(await y(selector)).toBeLessThan(await y(title))
  expect(await y(title)).toBeLessThan(await y(ahead))
  expect(await y(ahead)).toBeLessThan(await y(hotel))
  const notices = page.locator('.notices')
  expect(await y(hotel)).toBeLessThan(await y(notices))
  await notices.getByText('Keep in mind', { exact: true }).click()
  await expect(notices.locator('.notice')).toBeHidden()
  await notices.getByText('Keep in mind', { exact: true }).click()
  await expect(notices.locator('.notice').first()).toBeVisible()
  expect(await y(hotel)).toBeLessThan(await y(review))
  expect(await y(review)).toBeLessThan(await y(tomorrow))
  await page.getByRole('button', { name: /Covadonga Lakes/ }).first().click()
  await expect(page.getByRole('dialog')).toContainText('Covadonga Lakes, Buferrera and Sanctuary')
  await page.getByRole('button', { name: 'Close activity details' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.attention-row').first()).toBeVisible()
  await expect(page.locator('.timeline-marker').nth(1)).toContainText('Flex')
  const coastStop = page.locator('.timeline li').filter({ hasText: 'Day 2 optional coast stop' })
  await expect(coastStop.getByRole('button', { name: /Playa de Gulpiyuri/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)

  await route(page, 'today/day-1')
  await expect(page.locator('.day-review')).toContainText('Hotel El Jisu')
  await expect(page.locator('.day-review')).not.toContainText('Palacio de Avil\u00e9s')
  const arrivalChoice = page.locator('.choice-option').filter({ hasText: 'El Capricho' })
  await expect(arrivalChoice).toBeVisible()
  await arrivalChoice.getByRole('button', { name: /View details for El Capricho/ }).click()
  await expect(page.getByRole('dialog')).toContainText('El Capricho de Gaud\u00ed, Comillas')
  await expect(page.getByRole('dialog').getByRole('link', { name: /Navigate/ })).toBeVisible()
})

test('seed confirms reservations while keeping operational hotel checks pending', () => {
  expect(seed.stays.every((stay: { booking: { status: string } }) => stay.booking.status === 'booked')).toBe(true)
  expect(seed.actions.slice(0, 5).every((action: { status: string }) => action.status === 'pending')).toBe(true)
  for (const id of ['day-1-item-1', 'day-1-item-2', 'day-13-item-3', 'day-13-item-4']) {
    const item = seed.days.flatMap((day: { items: { id: string; booking?: { status: string } }[] }) => day.items).find((candidate: { id: string }) => candidate.id === id)
    expect(item?.booking?.status).toBe('booked')
  }
  expect(seed.actions.find((action: { id: string }) => action.id === 'action-6').status).toBe('pending')
})



test('hotel nights, stay booking, shared details and local note creation', async ({ page }) => {
  await ready(page)
  await route(page, 'new/day-3')
  await page.getByLabel('Type', { exact: true }).selectOption('hotel')
  await page.getByLabel('Name', { exact: true }).fill('Traveller hotel')
  await save(page)
  await expect(page.locator('.hotel-panel')).toContainText('Traveller hotel')
  await page.locator('.hotel-panel').getByRole('link', { name: 'Edit stay at Traveller hotel' }).click()
  await page.getByLabel('Check-in date').fill('')
  await page.getByLabel('Check-in date').fill('2026-09-22')
  await page.getByLabel('Check-out date').fill('2026-09-24')
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('17:00')
  await save(page)
  const result = JSON.parse((await exportData(page)).toString())
  const hotel = result.entities.find((e: { name: string }) => e.name === 'Traveller hotel')
  expect(result.days[0].stayId).toBe('stay-1')
  expect(result.days[1].stayId).toBe('stay-1')
  expect(result.days[2].stayId).toBe(result.days[3].stayId)
  await route(page, `entity/${hotel.id}`)
  await page.getByLabel('Breakfast', { exact: true }).fill('07:30 at reception')
  await save(page)
  for (const day of ['day-3', 'day-4']) {
    await route(page, `day/${day}`)
    await expect(page.locator('.hotel-panel')).toContainText('07:30 at reception')
    await expect(page.locator('.hotel-panel')).toContainText('Confirmed 17:00')
  }
  await route(page, 'new/day-4')
  await page.getByLabel('Type', { exact: true }).selectOption('note')
  await page.getByLabel('Name', { exact: true }).fill('Bring the picnic')
  await save(page)
  await expect(page.locator('.timeline')).toContainText('Bring the picnic')
  await page.screenshot({ path: 'test-results/phase2-day-phone.png' })
})
