import { expect, test, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
const seed = JSON.parse(readFileSync('src/data/initial-trip.json', 'utf8'))

async function ready(page: Page) {
  await page.goto('/')
  await page.evaluate(async () => { await navigator.serviceWorker.ready })
  await page.reload()
  await expect.poll(() => page.evaluate(() => Boolean(navigator.serviceWorker.controller))).toBe(true)
  if (await page.getByRole('button', { name: 'Dismiss', exact: true }).isVisible()) await page.getByRole('button', { name: 'Dismiss', exact: true }).click()
}
async function route(page: Page, path: string) { await page.evaluate(p => { location.hash = p }, `#/${path}`) }
async function save(page: Page) { await page.getByRole('button', { name: 'Save changes', exact: true }).click(); await expect(page.getByRole('button', { name: 'Save changes', exact: true })).toHaveCount(0) }
async function exportData(page: Page) {
  await route(page, 'more')
  const downloading = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export trip data', exact: true }).click()
  const stream = await (await downloading).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  return Buffer.concat(chunks)
}

test('offline CRUD, shared notes, booking propagation, move and exclusive alternatives', async ({ page, context }) => {
  await ready(page)
  await context.setOffline(true)
  await route(page, 'new/day-2')
  await page.getByLabel('Type', { exact: true }).selectOption('restaurant')
  await page.getByLabel('Name', { exact: true }).fill('Traveller lunch')
  await page.getByText('Place details & notes (optional)', { exact: true }).click()
  await page.getByLabel('Navigation link').fill('https://maps.google.com/?q=Llanes')
  await page.getByText('Booking details (optional)', { exact: true }).click()
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('13:15')
  await save(page)
  await expect(page.locator('.timeline').getByText('Traveller lunch', { exact: true }).first()).toBeVisible()
  const restaurant = page.locator('.timeline li').filter({ has: page.getByRole('heading', { name: 'Traveller lunch', exact: true }) })
  await expect(restaurant).toContainText('Confirmed 13:15')
  await restaurant.getByRole('link', { name: 'Edit visit', exact: true }).click()
  await page.getByLabel('Day', { exact: true }).selectOption('day-3')
  await save(page)
  await expect(page).toHaveURL(/day-3$/)
  const data = JSON.parse((await exportData(page)).toString())
  const entity = data.entities.find((e: { name: string }) => e.name === 'Traveller lunch')
  await route(page, `entity/${entity.id}`)
  await page.getByLabel('Place notes', { exact: true }).fill('Terrace if dry')
  await save(page)
  await page.reload()
  await expect(page.getByText('Terrace if dry', { exact: true })).toBeVisible()
  await route(page, 'item/day-3-item-2')
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('10:00')
  await page.getByLabel('Arrive before', { exact: true }).fill('09:30')
  await save(page)
  await route(page, 'more')
  const action = page.locator('.checklist>div').filter({ has: page.getByRole('heading', { name: 'El Soplao', exact: true }) })
  await expect(action).toContainText('Resolved')
  await route(page, 'day/day-12')
  await page.locator('.timeline li').filter({ hasText: 'Nature version — walk Las Xanas' }).getByRole('button', { name: 'Choose this option' }).click()
  await expect(page.locator('.timeline li').filter({ hasText: 'Culture version — go directly to Naranco' })).toContainText('skipped')
  await route(page, `entity/${entity.id}`)
  await page.getByRole('button', { name: 'Delete unused place' }).click()
  await expect(page.getByRole('alert')).toContainText('still used')
  const visit = data.days[2].items.find((i: { entityIds: string[] }) => i.entityIds.includes(entity.id))
  await route(page, `item/${visit.id}`)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Remove scheduled visit' }).click()
  await expect(page).toHaveURL(/day-3$/)
  await route(page, `entity/${entity.id}`)
  page.once('dialog', d => d.accept())
  await page.getByRole('button', { name: 'Delete unused place' }).click()
  await expect(page).toHaveURL(/explore$/)
  await page.reload()
  await page.getByRole('searchbox').fill('Traveller lunch')
  await expect(page.getByText('No places found.', { exact: false })).toBeVisible()
})

test('cross-context export/import, rejection, cancellation and atomic backup restore', async ({ page, browser }) => {
  await ready(page)
  await page.getByLabel('Day note', { exact: true }).fill('From phone one')
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Note saved')
  await route(page, 'documents')
  await page.getByRole('button', { name: 'Add shortcut', exact: true }).click()
  await page.getByLabel('Shortcut 1 name').fill('Trip folder')
  await page.getByLabel('Shortcut 1 URL').fill('https://drive.google.com/drive/folders/example')
  await save(page)
  const exported = await exportData(page)
  const second = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const receiver = await second.newPage()
  await receiver.goto('http://127.0.0.1:4173/#/more')
  const upload = receiver.getByLabel('Import trip data', { exact: true })
  await upload.setInputFiles({ name: 'broken.json', mimeType: 'application/json', buffer: Buffer.from('{ nope') })
  await expect(receiver.getByRole('status')).toContainText('not a compatible')
  await upload.setInputFiles({ name: 'future.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ ...seed, schemaVersion: 99 })) })
  await expect(receiver.getByRole('status')).toContainText('not a compatible')
  await upload.setInputFiles({ name: 'trip.json', mimeType: 'application/json', buffer: exported })
  await receiver.getByRole('button', { name: 'Cancel replacement' }).click()
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('')
  await upload.setInputFiles({ name: 'trip.json', mimeType: 'application/json', buffer: exported })
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  const result = JSON.parse((await exportData(receiver)).toString())
  const original = JSON.parse(exported.toString())
  expect({ ...result, revision: 0, updatedAt: '' }).toEqual({ ...original, revision: 0, updatedAt: '' })
  await receiver.getByRole('button', { name: 'Review pre-import backup' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('')
  await receiver.getByRole('button', { name: 'Review pre-import backup' }).click()
  await receiver.getByRole('button', { name: 'Confirm entire trip replacement' }).click()
  await expect(receiver.getByRole('status')).toContainText('Trip replaced')
  expect(JSON.parse((await exportData(receiver)).toString()).days[0].notes).toBe('From phone one')
  await second.close()
})

test('stale-tab writes retain the complete form draft and protect navigation', async ({ page, context }) => {
  await page.goto('/#/entity/restaurant-don-paco')
  await page.getByLabel('Place notes', { exact: true }).fill('Keep this private draft')
  page.once('dialog', d => d.dismiss())
  await page.getByRole('link', { name: 'More', exact: true }).click()
  await expect(page.getByLabel('Place notes', { exact: true })).toHaveValue('Keep this private draft')
  const other = await context.newPage()
  await other.goto('/')
  await other.getByLabel('Day note', { exact: true }).fill('Concurrent save')
  await other.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(other.getByRole('status')).toContainText('Note saved')
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('another tab')
  await expect(page.getByLabel('Place notes', { exact: true })).toHaveValue('Keep this private draft')
})

test('mobile form and browsing screens fit the viewport', async ({ page }) => {
  await page.goto('/#/new/day-1')
  await page.getByLabel('Type', { exact: true }).selectOption('hotel')
  await page.screenshot({ path: 'test-results/phase2-hotel-form.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  page.once('dialog', d => d.accept())
  await route(page, 'explore')
  await page.getByLabel('Type', { exact: true }).selectOption('activity')
  await page.getByLabel('Plan', { exact: true }).selectOption('alternative')
  await page.screenshot({ path: 'test-results/phase2-explore.png' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})



test('hotel nights, stay booking, shared details and local note creation', async ({ page }) => {
  await ready(page)
  await route(page, 'new/day-3')
  await page.getByLabel('Type', { exact: true }).selectOption('hotel')
  await page.getByLabel('Name', { exact: true }).fill('Traveller hotel')
  await save(page)
  await expect(page.locator('.hotel-panel')).toContainText('Traveller hotel')
  await page.locator('.hotel-panel').getByRole('link', { name: 'Edit stay & booking' }).click()
  await page.getByLabel('Check-in date').fill('')
  await page.getByLabel('Check-in date').fill('2026-09-22')
  await page.getByLabel('Check-out date').fill('2026-09-24')
  await page.getByLabel('Booking status', { exact: true }).selectOption('booked')
  await page.getByLabel('Booked time', { exact: true }).fill('17:00')
  await save(page)
  const result = JSON.parse((await exportData(page)).toString())
  const hotel = result.entities.find((e: { name: string }) => e.name === 'Traveller hotel')
  expect(result.days[0].stayId).toBe('stay-1')
  expect(result.days[1].stayId).toBe('stay-1')
  expect(result.days[2].stayId).toBe(result.days[3].stayId)
  await route(page, `entity/${hotel.id}`)
  await page.getByLabel('Breakfast', { exact: true }).fill('07:30 at reception')
  await save(page)
  for (const day of ['day-3', 'day-4']) {
    await route(page, `day/${day}`)
    await expect(page.locator('.hotel-panel')).toContainText('07:30 at reception')
    await expect(page.locator('.hotel-panel')).toContainText('Confirmed 17:00')
  }
  await route(page, 'new/day-4')
  await page.getByLabel('Type', { exact: true }).selectOption('note')
  await page.getByLabel('Name', { exact: true }).fill('Bring the picnic')
  await save(page)
  await expect(page.locator('.timeline')).toContainText('Bring the picnic')
  await page.screenshot({ path: 'test-results/phase2-day-phone.png' })
})
